/*
 * Reginald and the Sex Vampires for the Amstrad CPC
 * Copyright (C) 2025 Dave Moore
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; If not, see <http://www.gnu.org/licenses/>.
 */

#pragma once

#include "main.h"

/*
 * Font generated by CPC Telera with image_conversation.mk macros; each tile is
 * 8x8 pixels, which in Mode 1 is 2x8 bytes
 */
extern const u8 font_ts_00[2 * 8];
extern const u8 font_ts_01[2 * 8];
extern const u8 font_ts_02[2 * 8];
extern const u8 font_ts_03[2 * 8];
extern const u8 font_ts_04[2 * 8];
extern const u8 font_ts_05[2 * 8];
extern const u8 font_ts_06[2 * 8];
extern const u8 font_ts_07[2 * 8];
extern const u8 font_ts_08[2 * 8];
extern const u8 font_ts_09[2 * 8];
extern const u8 font_ts_10[2 * 8];
extern const u8 font_ts_11[2 * 8];
extern const u8 font_ts_12[2 * 8];
extern const u8 font_ts_13[2 * 8];
extern const u8 font_ts_14[2 * 8];
extern const u8 font_ts_15[2 * 8];
extern const u8 font_ts_16[2 * 8];
extern const u8 font_ts_17[2 * 8];
extern const u8 font_ts_18[2 * 8];
extern const u8 font_ts_19[2 * 8];
extern const u8 font_ts_20[2 * 8];
extern const u8 font_ts_21[2 * 8];
extern const u8 font_ts_22[2 * 8];
extern const u8 font_ts_23[2 * 8];
extern const u8 font_ts_24[2 * 8];
extern const u8 font_ts_25[2 * 8];
extern const u8 font_ts_26[2 * 8];
extern const u8 font_ts_27[2 * 8];
extern const u8 font_ts_28[2 * 8];
extern const u8 font_ts_29[2 * 8];
extern const u8 font_ts_30[2 * 8];
extern const u8 font_ts_31[2 * 8];
extern const u8 font_ts_32[2 * 8];
extern const u8 font_ts_33[2 * 8];
extern const u8 font_ts_34[2 * 8];
extern const u8 font_ts_35[2 * 8];
extern const u8 font_ts_36[2 * 8];
extern const u8 font_ts_37[2 * 8];
extern const u8 font_ts_38[2 * 8];
extern const u8 font_ts_39[2 * 8];
extern const u8 font_ts_40[2 * 8];
extern const u8 font_ts_41[2 * 8];
extern const u8 font_ts_42[2 * 8];
extern const u8 font_ts_43[2 * 8];
extern const u8 font_ts_44[2 * 8];
extern const u8 font_ts_45[2 * 8];
extern const u8 font_ts_46[2 * 8];
extern const u8 font_ts_47[2 * 8];
extern const u8 font_ts_48[2 * 8];
extern const u8 font_ts_49[2 * 8];
extern const u8 font_ts_50[2 * 8];
extern const u8 font_ts_51[2 * 8];
extern const u8 font_ts_52[2 * 8];
extern const u8 font_ts_53[2 * 8];
extern const u8 font_ts_54[2 * 8];
extern const u8 font_ts_55[2 * 8];
extern const u8 font_ts_56[2 * 8];
extern const u8 font_ts_57[2 * 8];
extern const u8 font_ts_58[2 * 8];
extern const u8 font_ts_59[2 * 8];
extern const u8 font_ts_60[2 * 8];
extern const u8 font_ts_61[2 * 8];
extern const u8 font_ts_62[2 * 8];
extern const u8 font_ts_63[2 * 8];
extern const u8 font_ts_64[2 * 8];
